### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3`

### CODE REVIEW

**Comment by luzpaz** [comment]
bump

**Comment by thliebig** [comment]
Sorry that I totally missed this PR. The readme have changes and the rst files too. Do you want to have another look at it. Otherwise I will have a go and hope to fix your patch...

**Comment by luzpaz** [comment]
I can't fix ATM, do you mind taking a stab at it ?

**Comment by thliebig** [comment]
I think this is out of date, please re-open if you disagree

**Comment by luzpaz** [comment]
Resubmitted in #117

**Pull request closed without merging**
